Update AboutUs and PPP
AY2122S2-CS2103T-W14-1/tp pull request #17
Opened 2022-02-23 18:51 UTC by yuqitanyq

2022-02-24 08:08 UTC, Halpfrog commented on docs/AboutUs.md
> +[[github](http://github.com/yuqitanyq)] [[portfolio](team/yuqitanyq.md)]
Take care to make sure that there won't be refactoring issues when we change links.

2022-02-24 08:10 UTC, Halpfrog requested changes
Change the links back to accessible ones to make sure they don't all links to the same profile.

2022-03-01 07:25 UTC, yl-ang reviewed
LGTM!

2022-03-01 07:25 UTC, yl-ang commented on docs/team/yuqitanyq.md
> +
LGTM!

2022-03-01 14:11 UTC, merged