Add Details Of User Guide (FAQ and Command Summary)
AY2122S2-CS2103T-W14-1/tp pull request #18
Opened 2022-02-23 18:56 UTC by yuqitanyq

2022-02-24 07:35 UTC, yl-ang commented on docs/UserGuide.md
> +| Category    | Format
The table format can be further broken down into 3 different categories.

2022-02-24 07:47 UTC, yl-ang requested changes
Changes to make to the command summary table.
See the comment in line 184 for the proposed changes.

2022-02-27 14:18 UTC, yuqitanyq commented
I have changed the Command Summary as proposed. However, I am not sure if the last command of the General commands is considered a command, as it is about clicking the up and down arrows, not typing in commands. Maybe we can discuss this as a team.

2022-03-01 07:17 UTC, yl-ang requested changes
Overall LGTM!

There might be some concern for the borrow and return commands under Book, we can review them over in the team meeting and make the changes

2022-03-01 07:17 UTC, yl-ang commented on docs/UserGuide.md
> +| **Return a book**         | `return [b/<index>] or [p/<index>]`                                            |
Not sure if we should merge b/index or p/index as one bubble for both the borrow and return command in the user guide.

There could be ambiguity in [index](https://nusu-my.sharepoint.com/:w:/r/personal/e0665491_u_nus_edu/Documents/Document.docx?d=w71ddd0adbc1c418fa7c2009a26c295fb&csf=1&web=1&e=G8Jed5&nav=eyJjIjo4NjcxNjAwMDB9).

If our user runs the command `return p/<index>`, is the index preferring to the index from the patron list or the book list?

Maybe we can add borrow and return for patron and for book respectively?

2022-03-01 07:17 UTC, yl-ang commented on docs/UserGuide.md
> +| **Navigating the different patrons/books** | **Clicking the up and down arrows** |
LGTM!

2022-03-01 07:17 UTC, yl-ang commented on docs/UserGuide.md
> +| **Delete a current book** | `book delete INDEX`                                                            |
LGTM!

2022-03-01 14:05 UTC, bingsen0806 approved these changes
LGTM! 👍

2022-03-01 14:06 UTC, yl-ang approved these changes

2022-03-01 14:07 UTC, merged