Branch UG DG Additions
AY2122S2-CS2103T-W14-1/tp pull request #211
Opened 2022-04-06 15:27 UTC by aditi2313

Changes to UG:
1. Tutorial addition to Quick Start section.
2. Removed sample commands to test under Quick Start.

Additions to DG:
1. Implementation details and design considerations for `patron overdue` command.
2. New sequence and activity diagrams for `patron overdue` command as part of implementation details.
3. DG Manual testing for `patron overdue` command. 
4. DG Product Scope changes
5. DG Non-functional requirement changes

2022-04-06 17:07 UTC, Halpfrog reviewed
LGTM

2022-04-06 17:07 UTC, Halpfrog commented on docs/diagrams/OverduePatronCommandSequenceDiagram.puml
> +@enduml
LGTM!

2022-04-07 00:24 UTC, yl-ang requested changes
Overall LGTM! The changes are good but I think your folk didn't contain the updated the updated changes from PED prs ><

2022-04-07 00:24 UTC, yl-ang commented on docs/UserGuide.md
> +</div>
Good use of alerts to tell the user to take note of the borrow command 👍

2022-04-07 00:24 UTC, yl-ang commented on docs/DeveloperGuide.md
> +
The testing looks good to me 💯

2022-04-07 00:24 UTC, yl-ang commented on docs/DeveloperGuide.md
> +
I like the addition of design consideration 💯

2022-04-07 00:24 UTC, yl-ang commented on docs/UserGuide.md
> +* `patron list`: You can view the list of patrons with their details in this list.
This is an old bug corrected from PED, the newer folk repo has updated 🤔

2022-04-07 03:20 UTC, yl-ang approved these changes
LGTM!

2022-04-07 03:20 UTC, merged