Add book package to include functionalities and objects representing books
AY2122S2-CS2103T-W14-1/tp pull request #48
Opened 2022-03-09 08:22 UTC by bingsen0806

Package book: Add Book class and classes representing fields of Book

There is lack of objects and utility classes representing books in a
library.

Our application requires such representations to be able to
keep track and store information of books.

Let's introduce the following classes in a separate book package to help
store information regarding books:
* Book - Representing a book with name, isbn, authors and category tags
* Author - Representing an author of a book
* ISBN - Representing the isbn of a book
* BookName - Representing the name of a book
* Add separate test classes to unit test each of the classes above

Each field is represented as a class so that we abide to the Open-Closed
Principle in SOLID. For example, Author may only contain a String now,
but we may extend Author to include other attributes of the author in
future.

All these information is encapsulated in a separate book package so as
to abide to the encapsulation principle of OOP.

2022-03-09 19:34 UTC, yl-ang requested changes
Overall it looks good to me but there are some changes that can be made such as the regular expression validation used to validate author names and book titles.

Keep up the good work 💯

2022-03-09 19:34 UTC, yl-ang commented on src/main/java/seedu/address/model/book/BookName.java
> +    public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} \\'\\:]*";
The check might fail if book names contain hyphens and other special characters.

2022-03-09 19:34 UTC, yl-ang commented on src/main/java/seedu/address/model/book/BookName.java
> +    public static final String MESSAGE_CONSTRAINTS =
Might need to update the constraint message to allow ":" and other special characters.

2022-03-09 19:34 UTC, yl-ang commented on src/main/java/seedu/address/model/book/Isbn.java
> +    }
Good computation of the checksum for ISBN with 10 digits!

2022-03-09 19:34 UTC, yl-ang commented on src/main/java/seedu/address/model/book/Isbn.java
> +    }
Good computation of the checksum for ISBN with 13 digits!

2022-03-09 19:36 UTC, yuqitanyq requested changes
Overall, I think most of the code looks good! However, there are some issues such as including the hyphens and special characters for regex validation. Also, there are some minor bugs in documentation and Javadocs.

2022-03-09 19:36 UTC, yuqitanyq commented on src/main/java/seedu/address/model/book/BookName.java
> +    public static final String VALIDATION_REGEX = "[\\p{Alnum}][\\p{Alnum} \\'\\:]*";
This is a good validation, but there may be book titles with question marks and hyphen. Perhaps, we could include this in the regex or include this restriction in the string MESSAGE_CONSTRAINTS.

2022-03-09 19:36 UTC, yuqitanyq commented on src/main/java/seedu/address/model/book/BookName.java
> +     */
The message and javadocs need to be changed as well to reflect the reflections as explained below on the restrictions for the book names.

2022-03-10 00:05 UTC, yl-ang approved these changes

2022-03-10 00:06 UTC, bingsen0806 commented on src/main/java/seedu/address/model/book/Book.java
> +                && otherBook.getIsbn().equals(getIsbn());
No, this will not return false. This is because the equality is handled inside `Isbn::isequal`

2022-03-10 00:07 UTC, bingsen0806 commented on src/main/java/seedu/address/model/AddressBook.java
> +        books = new BookList();
Yes, it is intentional. This BookList can contain duplicates.

2022-03-10 00:08 UTC, yuqitanyq approved these changes

2022-03-10 00:10 UTC, merged